/**
 * Created by Administrator on 2020/10/28.
 */
var mongoose= require('mongoose');
Schema=mongoose.Schema;
var GameSchema=new Schema({
    //房间相关
    roomID:{
        type:String,
    },
    hostName:{
        type:String
    },
    gameName:{
        type:String
    },
    roomState:{
        type:Number
    },
    gameType:{
        type:Number
    },
    gameTime:{
        type:Number
    },
    //玩家
    players:[
        {
            playerName:{
                type:String
            },
            playerTimeA:{
                type:Number
            },
            playerTimeB:{
                type:Number
            }
        }
    ],
    //游戏内容
    gameVersion:{
        type:String
    },
    gameID:{
        type:String,
        unique:true,
    },
    gameDate:{
        type:String
    },
    gameMenu:[
        {
            type:String
        }        
    ],
    gameBoards:[
        {
            type:String
        }  
    ],
    gameResult:{
        winnerteam:{
            type:Number
        },
        winner:[
            {
                type:String
            }
        ],
        loser:[
            {
                type:String
            }
        ],
        drawer:[
            {
                type:String
            }
        ]
    }
});
exports.GameSchema=GameSchema;